name: Auto Create Proxmox VM

on:
  push:
    paths:
      - "new-member/**"

jobs:
  create_vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Detect new member file
        id: changed
        run: |
          FILE=$(git diff --name-only HEAD~1 HEAD | grep new-member)
          BASENAME=$(basename "$FILE")
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Run Ansible on controller
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ANSIBLE_HOST }}
          username: ansible
          key: ${{ secrets.ANSIBLE_KEY }}
          script: |
            export NEW_MEMBER_FILE="${{ steps.changed.outputs.file }}"
            export PROXMOX_PASSWORD="${{ secrets.PROXMOX_PASSWORD }}"
            cd /etc/ansible
            git pull
            ansible-playbook create_vm.yml
